/** ISO 3166-1 alpha-2 → sovereign / administering state (common English name). Omitted or null where disputed or not applicable.
 *  Must stay in sync with `colonizer` on non-independent rows in `src/data/countries.json`. */
export const TERRITORY_COLONIZER_BY_ISO2: Record<string, string> = {
  AX: "Finland",
  AS: "United States",
  AI: "United Kingdom",
  AW: "Netherlands",
  BM: "United Kingdom",
  BV: "Norway",
  IO: "United Kingdom",
  VG: "United Kingdom",
  BQ: "Netherlands",
  KY: "United Kingdom",
  CX: "Australia",
  CC: "Australia",
  CK: "New Zealand",
  CW: "Netherlands",
  FK: "United Kingdom",
  FO: "Denmark",
  GF: "France",
  PF: "France",
  TF: "France",
  GI: "United Kingdom",
  GL: "Denmark",
  GP: "France",
  GU: "United States",
  GG: "United Kingdom",
  HM: "Australia",
  HK: "China",
  IM: "United Kingdom",
  JE: "United Kingdom",
  MO: "China",
  MQ: "France",
  YT: "France",
  MS: "United Kingdom",
  NC: "France",
  NU: "New Zealand",
  NF: "Australia",
  MP: "United States",
  PN: "United Kingdom",
  PR: "United States",
  RE: "France",
  BL: "France",
  SH: "United Kingdom",
  MF: "France",
  PM: "France",
  SX: "Netherlands",
  GS: "United Kingdom",
  SJ: "Norway",
  TK: "New Zealand",
  TC: "United Kingdom",
  UM: "United States",
  VI: "United States",
  WF: "France",
};
