export type Country = {
  iso2: string;
  iso3: string;
  name: string;
  officialName: string | null;
  countryCreationDate: string | null;
  independenceDate: string | null;
  altSpellings: string[];
  population: number | null;
  region: string | null;
  subregion: string | null;
  unMember: boolean | null;
  status: string | null;
  borders: string[];
  continents: string[];
  capital: string | null;
  areaKm2: number | null;
  latlng: [number, number] | null;
  drivingSide: string | null;
  callingCodes: string[];
  internetTlds: string[];
  googleMapsUrl: string | null;
  openStreetMapsUrl: string | null;
  wikipediaUrl: string;
  languages: string[];
  currencies: string[];
  timezones: string[];
  independent: boolean | null;
  landlocked: boolean | null;
  startOfWeek: string | null;
  flagPath: string;
  markerLng: number | null;
  markerLat: number | null;
};
